### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by majid0jalili** [cdsc-github/parade-ara-simulator#1]
Hi and thanks for releasing the simulator,

Actually, I build the simulator for ARA version. Now, when I run the simulator using following command:
./build/X86/gem5.opt ./configs/example/fs.py

I got this error:

info: Entering event queue @ 0.  Starting simulation...
Floating point exception (core dumped)

I checked with gdb and I found the problem is in  line 34 of NetworkInterrupts.cc: 
Program received signal SIGFPE, Arithmetic exception.
localCBsForCycle (current_cycle=current_cycle@entry=...) at build/X86/modules/NetworkInterrupt/NetworkInterrupts.cc:34
34        size_t oldIndex = (m_current_cycle - 1) % cycleCBRing.size();

Do you have any suggestion for me?

**Comment by zhenman** [comment]
Hi Majid,

Thanks for your interest in using PARADE. 

Due to some porting issues, currently PARADE uses a separate event queue for accelerator events, which is the variable cycleCBRing. I think you got this error because cycleCBRing is not initialized. 

When you build ARA version, did you enable the macro SIM_DEDICATED_ARA in all files? This could be the possible reason because the initialization of cycleCBRing is under the SIM_DEDICATED_ARA macro.

Please let me know if there is more problems.

Thanks,
Zhenman

**Comment by majid0jalili** [comment]
Thanks,

I enabled all the macros in three files..but nothing changed. I changed the code as follows:
 size_t aa = cycleCBRing.size();
  if(aa<=0) aa=1;

but, the error goes to next if statement.

**Comment by zhenman** [comment]
It looks like that cycleCBRing is still not initialized. What command did you run? Did you exactly follow the steps in README.md?

**Comment by majid0jalili** [comment]
You r right!..I missed some things. I compiled and created the checkpoints. However, I must mention some minor things about the scripts (maybe they are OK in other machines):
1) Some scripts create same name for the output folder with the name of ARA executable which causes some errors.

2) In compile-time, there is an error due to the lack of README file.. I change the name of README.md to README, It went OK.

3) In README.md the "cp buid/X86/gem5.opt parade-test/" should be changed to "cp build/X86/gem5.opt parade-test/"; buid-->build (source of error for hasty people :D). 

Best
Majid

**Comment by zhenman** [comment]
Great that it works. For number 2), it's strange. I will correct the typo.

Thanks,
Zhenman

**Comment by Nirmalk87** [comment]
Hello,
I followed the instructions from the README.md file but I ran into the same issue. Listed below. 

Program received signal SIGFPE, Arithmetic exception.
localCBsForCycle (current_cycle=current_cycle@entry=...) at build/X86/modules/NetworkInterrupt/NetworkInterrupts.cc:37
37        size_t oldIndex = (m_current_cycle - 1) % cycleCBRing.size();

@majid0jalili @zhenman could you please share the steps used to fix this issue?

Thanks.
